name: GitHub Engineering Analytics


on:
  schedule:
    - cron: "0 0 * * *" # Se actualiza automáticamente cada medianoche
  workflow_dispatch: # Permite ejecutar la acción de forma manual

jobs:
  generate-analytics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v3
        
      - name: GitHub Engineering Analytics
        uses: maharudraabhishek/maharudraabhishek@v1.0
        with:
          insert-readme-markers: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
